# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/workspace/EmbeddedSystemNJU2018-Demo/examples/GPIO

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/workspace/EmbeddedSystemNJU2018-Demo/examples/GPIO

# Include any dependencies generated for this target.
include CMakeFiles/../../lib/GPIOlib.h.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/../../lib/GPIOlib.h.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/../../lib/GPIOlib.h.dir/flags.make

CMakeFiles/../../lib/GPIOlib.h.dir/requires:

.PHONY : CMakeFiles/../../lib/GPIOlib.h.dir/requires

CMakeFiles/../../lib/GPIOlib.h.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/../../lib/GPIOlib.h.dir/cmake_clean.cmake
.PHONY : CMakeFiles/../../lib/GPIOlib.h.dir/clean

CMakeFiles/../../lib/GPIOlib.h.dir/depend:
	cd /home/pi/workspace/EmbeddedSystemNJU2018-Demo/examples/GPIO && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/pi/workspace/EmbeddedSystemNJU2018-Demo/examples/GPIO /home/pi/workspace/EmbeddedSystemNJU2018-Demo/examples/GPIO /home/pi/workspace/EmbeddedSystemNJU2018-Demo/examples/GPIO /home/pi/workspace/EmbeddedSystemNJU2018-Demo/examples/GPIO /home/pi/workspace/EmbeddedSystemNJU2018-Demo/examples/lib/GPIOlib.h.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/../../lib/GPIOlib.h.dir/depend

